image:
  registry: docker.io
  repository: kubetm/database-service   # kubetm -> 개인 <docker id>로 변경
  tag: latest
# docker build -t kubetm/database-service:latest

tomcatAllowRemoteManagement: 1

persistence:
  enabled: false

service:
  type: NodePort
  nodePort: "30081"  # dev(30081), qa(30082), prod(30083)

extraEnvVars:
  - name: JAVA_OPTS
    value: '-Dspring.profiles.active=dev'